### PR TITLE
Added background subtraction

### PR DESCRIPTION
**Pull request by gdujany**
All the code to compute the energy test with background subtraction is there. Just need to set defaults values and options so that it defaults to the code without background subtraction

### CODE REVIEW

**Comment by gdujany** [comment]
I solved the inconsistency and committed the code that now lgtm. Will, when you have time have a look and if you are happy merge the pull request.

**Comment by gdujany** [comment]
Superseded by branch [tests](https://github.com/gdujany/pyManet/tree/tests)

**Review by WilliamBarter — COMMENTED** [review]
Looks good to me. I ran 20 times and saw no differences between original code and yours in case of no background subtraction, and my code and yours in case of background subtraction.

My one suggestion is to set the --signals argument to have type float.

We should also think it we can calculate meaningful Tis.txt for the background subtraction test. At the moment they are the same for the fast and slow methods - but I'm not sure how much meaning they have.

**Comment by gdujany** [comment]
I changed --signal to float and added some tests in #3 if you happy accept that merge request. For the `Tis` I am not sure there is much you can do more, maybe print also the `Tis` for the background so one can add them with a negative weight in an histogram? Anyway I would start merging what we have and leave it for the future

**Comment by WilliamBarter** [comment]
Sounds good.

**Pull request closed without merging**
